project "PhysX"
	kind "StaticLib"
	language "C++"
	cppdialect "C++17"
	staticruntime "off"
	location (vendorProjectFiles)
	targetdir (vendorOutputdir)
	objdir (vendorIntOutputdir)

	includedirs {
		"%{physxDir}/physx/include",
		"%{physxDir}/physx/source/common/include",
		"%{physxDir}/physx/source/common/src",
		"%{physxDir}/physx/source/physx/src",
		"%{physxDir}/physx/source/physx/src/device",
		"%{physxDir}/physx/source/physx/src/buffering",
		"%{physxDir}/physx/source/physxgpu/include",
		"%{physxDir}/physx/source/geomutils/include",
		"%{physxDir}/physx/source/geomutils/src",
		"%{physxDir}/physx/source/geomutils/src/contact",
		"%{physxDir}/physx/source/geomutils/src/common",
		"%{physxDir}/physx/source/geomutils/src/convex",
		"%{physxDir}/physx/source/geomutils/src/distance",
		"%{physxDir}/physx/source/geomutils/src/sweep",
		"%{physxDir}/physx/source/geomutils/src/gjk",
		"%{physxDir}/physx/source/geomutils/src/intersection",
		"%{physxDir}/physx/source/geomutils/src/mesh",
		"%{physxDir}/physx/source/geomutils/src/hf",
		"%{physxDir}/physx/source/geomutils/src/pcm",
		"%{physxDir}/physx/source/geomutils/src/ccd",
		"%{physxDir}/physx/source/geomutils/include",
		"%{physxDir}/physx/source/lowlevel/api/include",
		"%{physxDir}/physx/source/lowlevel/common/include/utils",
		"%{physxDir}/physx/source/lowlevel/software/include",
		"%{physxDir}/physx/source/lowlevel/common/include/pipeline",
		"%{physxDir}/physx/source/lowlevelaabb/include",
		"%{physxDir}/physx/source/lowleveldynamics/include",
		"%{physxDir}/physx/source/simulationcontroller/include",
		"%{physxDir}/physx/source/simulationcontroller/src",
		"%{physxDir}/physx/source/physxcooking/src",
		"%{physxDir}/physx/source/physxcooking/src/mesh",
		"%{physxDir}/physx/source/physxcooking/src/convex",
		"%{physxDir}/physx/source/scenequery/include",
		"%{physxDir}/physx/source/physxmetadata/core/include",
		"%{physxDir}/physx/source/immediatemode/include",
		"%{physxDir}/physx/source/pvd/include",
	}

	files {
		"%{physxDir}/physx/source/physx/src/NpActor.cpp",
		"%{physxDir}/physx/source/physx/src/NpAggregate.cpp",
		"%{physxDir}/physx/source/physx/src/NpArticulationJointReducedCoordinate.cpp",
		"%{physxDir}/physx/source/physx/src/NpArticulationReducedCoordinate.cpp",
		"%{physxDir}/physx/source/physx/src/NpArticulationSensor.cpp",
		"%{physxDir}/physx/source/physx/src/NpArticulationTendon.cpp",
		"%{physxDir}/physx/source/physx/src/NpArticulationSensor.cpp",
		"%{physxDir}/physx/source/physx/src/NpBounds.cpp",
		"%{physxDir}/physx/source/physx/src/NpCheck.cpp",
		"%{physxDir}/physx/source/physx/src/NpConstraint.cpp",
		"%{physxDir}/physx/source/physx/src/NpDebugViz.cpp",
		"%{physxDir}/physx/source/physx/src/NpCheck.cpp",
		"%{physxDir}/physx/source/physx/src/NpFactory.cpp",
		"%{physxDir}/physx/source/physx/src/NpFEMCloth.cpp",
		"%{physxDir}/physx/source/physx/src/NpFEMClothMaterial.cpp",
		"%{physxDir}/physx/source/physx/src/NpFEMSoftBodyMaterial.cpp",
		"%{physxDir}/physx/source/physx/src/NpFLIPMaterial.cpp",
		"%{physxDir}/physx/source/physx/src/NpHairSystem.cpp",
		"%{physxDir}/physx/source/physx/src/NpMaterial.cpp",
		"%{physxDir}/physx/source/physx/src/NpMetaData.cpp",
		"%{physxDir}/physx/source/physx/src/NpMPMMaterial.cpp",
		"%{physxDir}/physx/source/physx/src/NpParticleSystem.cpp",
		"%{physxDir}/physx/source/physx/src/NpPBDMaterial.cpp",
		"%{physxDir}/physx/source/physx/src/NpPhysics.cpp",
		"%{physxDir}/physx/source/physx/src/NpPruningStructure.cpp",
		"%{physxDir}/physx/source/physx/src/NpPvdSceneClient.cpp",
		"%{physxDir}/physx/source/physx/src/NpPvdSceneQueryCollector.cpp",
		"%{physxDir}/physx/source/physx/src/NpRigidDynamic.cpp",
		"%{physxDir}/physx/source/physx/src/NpRigidStatic.cpp",
		"%{physxDir}/physx/source/physx/src/NpScene.cpp",
		"%{physxDir}/physx/source/physx/src/NpSceneFetchResults.cpp",
		"%{physxDir}/physx/source/physx/src/NpSceneQueries.cpp",
		"%{physxDir}/physx/source/physx/src/NpSerializerAdapter.cpp",
		"%{physxDir}/physx/source/physx/src/NpShape.cpp",
		"%{physxDir}/physx/source/physx/src/NpShapeManager.cpp",
		"%{physxDir}/physx/source/physx/src/NpSoftBody.cpp",
		"%{physxDir}/physx/source/physx/src/PvdPhysicsClient.cpp",

		"%{physxDir}/physx/source/physx/src/omnipvd/NpOmniPvd.cpp",
		"%{physxDir}/physx/source/physx/src/omnipvd/NpOmniPvdRegistrationData.cpp",
		"%{physxDir}/physx/source/physx/src/omnipvd/OmniPvdPxSampler.cpp",
		"%{physxDir}/physx/source/physx/src/omnipvd/OmniPvdChunkAlloc.cpp",

		"%{physxDir}/physx/source/physx/src/gpu/PxGpu.cpp",
		"%{physxDir}/physx/source/physx/src/gpu/PxPhysXGpuModuleLoader.cpp",
		"%{physxDir}/physx/source/immediatemode/src/NpImmediateMode.cpp",
		"%{physxDir}/physx/source/physxmetadata/core/src/PxMetaDataObjects.cpp",
		"%{physxDir}/physx/source/physxmetadata/core/src/PxAutoGeneratedMetaDataObjects.cpp",
	}

	defines {
		"PX_PHYSX_GPU_SHARED_LIB_NAME=PhysXGpu_64.dll",
		"PX_PHYSX_STATIC_LIB",
		"PX_SUPPORT_PVD=1"
	}

	links {
		"LowLevel",
		"LowLevelAABB",
		"LowLevelDynamics",
		"PhysXCommon",
		"PhysXFoundation",
		"PhysXExtensions",
		"PhysXPvdSDK",
		"PhysXTask",
	}

	filter "system:linux"
		pic "On"
		systemversion "latest"
		files {
			"%{physxDir}/physx/source/physx/src/device/linux/PhysXIndicatorLinux.cpp",
		}
		
	filter "system:windows"
		systemversion "latest"
		defines {
			"WIN32",
			"WIN64",
			"_CRT_SECURE_NO_DEPRECATE",
			"_CRT_NONSTDC_NO_DEPRECATE",
			"_WINSOCK_DEPRECATED_NO_WARNINGS",
		}
		files {
			"%{physxDir}/physx/source/physx/src/windows/NpWindowsDelayLoadHook.cpp",
			"%{physxDir}/physx/source/physx/src/device/windows/PhysXIndicatorWindows.cpp"
		}

		links {
			"kernel32.lib",
			"user32.lib",
			"gdi32.lib",
			"winspool.lib",
			"shell32.lib",
			"ole32.lib",
			"oleaut32.lib",
			"uuid.lib",
			"comdlg32.lib",
			"advapi32.lib",
		}

	filter "configurations:Debug"
		runtime "Debug"
		symbols "on"
		optimize "off"
		defines {
			"PX_DEBUG=1",
			"PX_CHECKED=1",
			"PX_NVTX=0",
			"_DEBUG"
		}

	filter "configurations:Release"
		runtime "Release"
		optimize "on"
		symbols "on"
		defines {
			"_HAS_ITERATOR_DEBUGGING=0",
			"_ITERATOR_DEBUG_LEVEL=0",
			"PX_CHECKED=1",
			"PX_NVTX=0",
			"NDEBUG"
		}

	filter "configurations:Dist"
		runtime "Release"
		optimize "on"
		symbols "off"
		defines {
			"_HAS_ITERATOR_DEBUGGING=0",
			"_ITERATOR_DEBUG_LEVEL=0",
			"PX_CHECKED=1",
			"NDEBUG"
		}